
FROM eaps-docker-coldfusion.bintray.io/cf/coldfusion:latest
 
USER root
ENV acceptEULA YES
ENV password ColdFusion123
ENV enableSecureProfile true
# ssh
ENV SSH_PASSWD "root:Docker!"
ENV CF_PASSWD "cfuser:ColdFusion123"

RUN apt-get update \
	&& apt-get install -y apt-utils \
          unzip \
          openssh-server \
          vim \
          curl \
          wget \
          tcptraceroute \
	&& echo "$SSH_PASSWD" | chpasswd 

COPY sshd_config /etc/ssh/

#
#   Copy the application
#
#COPY index.cfm /opt/coldfusion/cfusion/wwwroot/CFIDE/
#COPY coldfusion.env /opt/coldfusion/cfusion/wwwroot/CFIDE/

COPY init_container.sh /usr/local/bin/
RUN chmod u+x /usr/local/bin/init_container.sh \
     && chmod 777 /opt  \
     && echo "$SSH_PASSWD" | chpasswd \
     && echo "cd /home" >> /etc/bash.bashrc

RUN mkdir -p /home/LogFiles \
     && ln -s /home/LogFiles /opt/coldfusion/cfusion/logs \
     && chmod 777 /home/LogFiles \
     && echo "$SSH_PASSWD" | chpasswd \
     && echo "cd /home" >> /etc/bash.bashrc
#
#   Dont expose any other port
#
ENV SSH_PORT 2222
EXPOSE 2222

ENTRYPOINT ["/usr/local/bin/init_container.sh"]